# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: active_tool 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "active_tool"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Joey Lin"]
  s.date = "2014-06-19"
  s.description = "A Tool Demo"
  s.email = "joeyoooooo@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "lib/active_tool.rb",
    "lib/active_tool/associate.rb",
    "lib/active_tool/associate/mongo_proxy.rb",
    "lib/active_tool/associate/proxy.rb",
    "lib/active_tool/ext.rb",
    "lib/active_tool/ext/array.rb",
    "lib/active_tool/ext/fixnum.rb",
    "lib/active_tool/ext/hash.rb",
    "lib/active_tool/ext/module.rb",
    "lib/active_tool/ext/string.rb",
    "lib/active_tool/ext/zip.rb",
    "lib/active_tool/fake_model.rb",
    "lib/active_tool/mongo_base.rb",
    "lib/active_tool/mongo_cache.rb",
    "lib/active_tool/rand_mode.rb",
    "lib/active_tool/rand_mode/factory.rb",
    "lib/active_tool/rand_mode/levelable.rb",
    "lib/active_tool/rand_mode/randable.rb",
    "lib/active_tool/redis_cache.rb",
    "lib/active_tool/redis_global.rb",
    "lib/active_tool/redis_lock.rb",
    "lib/active_tool/relation_prob.rb"
  ]
  s.homepage = "https://github.com/andyss/active_tool"
  s.rubygems_version = "2.2.2"
  s.summary = "A Tool Demo"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

